sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: rlr12138

  minioss:
    endpoint: http://192.168.125.131:9000
    access-key-id: root
    access-key-secret: rlr12138
    bucket-name: sky-take-out
  redis:
    host: 192.168.125.131
    port: 6379
    password: 123321
    database: 1
  wechat:
    appid: wx2b41639eb192a8d3
    secret: 0801217f6878d903dd36f2fc539e9d1f
    url-for-openid: https://api.weixin.qq.com/sns/jscode2session