sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: rlr12138

  minioss:
    endpoint: http://192.168.125.131:9000
    access-key-id: root
    access-key-secret: rlr12138
    bucket-name: sky-take-out